# Generated by Django 5.2.8 on 2025-12-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reg',
            fields=[
                ('accno', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=15)),
                ('amount', models.BigIntegerField()),
                ('address', models.CharField(max_length=100)),
                ('mobileno', models.BigIntegerField(max_length=10)),
            ],
        ),
    ]
