# Generated by Django 5.2.8 on 2025-12-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
