# Generated by Django 5.2.8 on 2025-12-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_alter_reg_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
